export const events = [
  {
    image: "/images/event1.png",
    title: "PyCon US 2026",
    slug: "pycon-us-2026",
    location: "Long Beach Convention & Entertainment Center, Long Beach, CA",
    date: "May 13-19, 2026",
    time: "9:00 AM PDT",
  },
  {
    image: "/images/event2.png",
    title: "DevOpsDays Austin 2026",
    slug: "devopsdays-austin-2026",
    location: "TCEA Conference Center, Austin, TX",
    date: "May 5-6, 2026",
    time: "9:00 AM CDT",
  },
  {
    image: "/images/event3.png",
    title: "WWDC26",
    slug: "wwdc26",
    location: "Apple Park, Cupertino, CA",
    date: "June 8-12, 2026",
    time: "All day",
  },
  {
    image: "/images/event4.png",
    title: "JSNation 2026",
    slug: "jsnation-2026",
    location: "Amsterdam, Netherlands",
    date: "June 11 & 15, 2026",
    time: "9:30 AM CEST",
  },
  {
    image: "/images/event5.png",
    title: "React Summit 2026",
    slug: "react-summit-2026",
    location: "Amsterdam, Netherlands",
    date: "June 12 & 16, 2026",
    time: "9:30 AM CEST",
  },
  {
    image: "/images/event6.png",
    title: "AWS re:Invent 2026",
    slug: "aws-reinvent-2026",
    location: "Las Vegas, NV",
    date: "Nov 30-Dec 4, 2026",
    time: "8:00 AM PST",
  },
  {
    image: "/images/event-full.png",
    title: "GITEX GLOBAL 2026",
    slug: "gitex-global-2026",
    location: "Expo City Dubai, Dubai, UAE",
    date: "Dec 7-11, 2026",
    time: "10:00 AM GST",
  },
] as const;
